=== NorthArrowResearch/riverscapes-programs/XSD/V1/Program.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Program" type="ProgramType"/>

  <xs:complexType name="ProgramType">
    <xs:sequence>
      <xs:element type="MetaDataType" name="MetaData" maxOccurs="1" minOccurs="0"/>
      <xs:element type="DefinitionsType" name="Definitions" maxOccurs="1" minOccurs="1"/>
      <xs:element type="HierarchyType" name="Hierarchy" maxOccurs="1" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
  </xs:complexType>

  <!--Hierarchy stuff-->
  <xs:complexType name="HierarchyType">
    <xs:choice>
      <xs:element type="FolderType" name="Collection" maxOccurs="1"/>
      <xs:element type="FolderType" name="Group" maxOccurs="unbounded"/>
      <xs:element type="ProductType" name="Product" maxOccurs="1"/>
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="FolderType">
    <xs:choice maxOccurs="unbounded">
      <xs:element type="FolderType" name="Collection" maxOccurs="1" minOccurs="0"/>
      <xs:element type="FolderType" name="Group" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="ProductType" name="Product" maxOccurs="unbounded" minOccurs="0"/>
    </xs:choice>
    <xs:attribute type="xs:string" name="ref" use="required"/>
  </xs:complexType>

  <xs:complexType name="ProductType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="ref" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="MetaType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="MetaDataType">
    <xs:sequence>
      <xs:element type="MetaType" name="Meta" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <!--HEre's where the definitions go-->
  <xs:complexType name="DefinitionsType">
    <xs:sequence>
      <xs:element type="CollectionsDefType" name="Collections" maxOccurs="1" minOccurs="1"/>
      <xs:element type="GroupsDefType" name="Groups" maxOccurs="1" minOccurs="1"/>
      <xs:element type="ProductsDefType" name="Products" maxOccurs="1" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CollectionsDefType">
    <xs:sequence>
      <xs:element type="CollectionDefType" name="Collection" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CollectionDefType">
    <xs:sequence>
      <xs:element type="AllowType" name="Allow" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:anyURI" name="url" use="optional"/>
  </xs:complexType>

  <xs:complexType name="AllowType">
    <xs:attribute type="xs:string" name="pattern"/>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="aliases" use="optional"/>
    <xs:attribute type="xs:string" name="folder"/>
  </xs:complexType>

  <xs:complexType name="GroupsDefType">
    <xs:sequence>
      <xs:element type="GroupDefType" name="Group" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="GroupDefType">
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="folder" use="required"/>
    <xs:attribute type="xs:anyURI" name="url" use="optional"/>
  </xs:complexType>

  <xs:complexType name="ProductsDefType">
    <xs:sequence>
      <xs:element type="ProductDefType" name="Product" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ProductDefType">
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="folder" use="required"/>
    <xs:attribute type="xs:anyURI" name="url" use="optional"/>
  </xs:complexType>

</xs:schema>

=== NorthArrowResearch/riverscapes-programs/CHaMP/program.xml
<?xml version="1.0" encoding="utf-8"?>
<Program name="CHaMP" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../XSD/V1/Program.xsd">
<MetaData>
  <Meta name="projectfile">project.rs.xml</Meta>
  <Meta name="cognitoUserpoolId">us-west-2_5LnOSGlts</Meta>
  <Meta name="cognitoWebclientId">rsfn72s12uoe8a0h2h58rsq9i</Meta>
  <Meta name="cognitoRegion">us-west-2</Meta>
  <Meta name="apiUrl">https://abgo77bhnc.execute-api.us-west-2.amazonaws.com/dev/api</Meta>
  <Meta name="projectXSD">https://gist.githubusercontent.com/MattReimer/8632b6ab88d5be7c2a034eb8bb563c6c/raw/CHaMP_Program.xsd</Meta>
</MetaData>

<Definitions>
  <!--Here's where we say what's allowed for each collection. Can be a list or a regex-->
  <Collections>
    <Collection id="COL_WATERSHED" name="Watershed">
      <Allow name="Asotin" folder="Asotin"/>
      <Allow name="Brownlee Reservoir" folder="BrownleeReservoir"/>
      <Allow name="Big Navarro Garcia" folder="BigNavarroGarcia" aliases="Big-Navarro-Garcia(CA)"/>
      <Allow name="Clearwater" folder="Clearwater"/>
      <Allow name="Entiat" folder="Entiat"/>
      <Allow name="Hells Canyon" folder="HellsCanyon"/>
      <Allow name="Imnaha" folder="Imnaha"/>
      <Allow name="John Day" folder="JohnDay"/>
      <Allow name="Klickitat" folder="Klickitat"/>
      <Allow name="Lemhi" folder="Lemhi"/>
      <Allow name="Little Salmon" folder="LittleSalmon"/>
      <Allow name="Lochsa" folder="Lochsa"/>
      <Allow name="Lolo" folder="Lolo"/>
      <Allow name="Lower Clearwater" folder="LowerClearwater" aliases="LowerClearwater"/>
      <Allow name="Lower Grande Ronde" folder="LowerGrandeRonde"/>
      <Allow name="Lower John Day" folder="LowerJohnDay"/>
      <Allow name="Lower Middle Fork Salmon" folder="LowerMiddleForkSalmon"/>
      <Allow name="Lower North Fork Clearwater" folder="LowerNorthForkClearwater"/>
      <Allow name="Lower Salmon" folder="LowerSalmon"/>
      <Allow name="Lower Selway" folder="LowerSelway"/>
      <Allow name="Lower Snake-Asotin" folder="Asotin"/>
      <Allow name="Lower Snake-Tucannon" folder="Tucannon"/>
      <Allow name="Lower Yakima" folder="LowerYakima"/>
      <Allow name="Methow" folder="Methow"/>
      <Allow name="Middle Fork Clearwater" folder="MiddleForkClearwater"/>
      <Allow name="Middle Columbia-Lake Wallula" folder="LakeWallula"/>
      <Allow name="Middle Fork John Day" folder="MiddleForkJohnDay"/>
      <Allow name="Middle Salmon-Chamberlain" folder="MiddleSalmonChamberlain"/>
      <Allow name="Middle Salmon-Panther" folder="MiddleSalmonPanther"/>
      <Allow name="Minam" folder="Minam"/>
      <Allow name="Naches" folder="Naches"/>
      <Allow name="North Fork John Day" folder="NorthForkJohnDay"/>
      <Allow name="Okanogan" folder="Okanogan"/>
      <Allow name="Pahsimeroi" folder="Pahsimeroi"/>
      <Allow name="Secesh" folder="Secesh"/>
      <Allow name="South Fork Clearwater" folder="SouthForkClearwater"/>
      <Allow name="South Fork Salmon" folder="SouthForkSalmon" aliases="SouthForkSalmon"/>
      <Allow name="South Fork John Day" folder="SouthForkJohnDay"/>
      <Allow name="Tucannon" folder="Tucannon"/>
      <Allow name="Umatilla" folder="Umatilla"/>
      <Allow name="Upper Grande Ronde" folder="UpperGrandeRonde" aliases="UpperGrandeRonde"/>
      <Allow name="Upper John Day" folder="UpperJohnDay"/>
      <Allow name="Upper Middle Fork Salmon" folder="UpperMiddleForkSalmon"/>
      <Allow name="Upper North Fork Clearwater" folder="UpperNorthForkClearwater"/>
      <Allow name="Upper Salmon" folder="UpperSalmon"/>
      <Allow name="Upper Selway" folder="UpperSelway"/>
      <Allow name="Upper Yakima" folder="UpperYakima"/>
      <Allow name="Walla Walla" folder="WallaWalla" aliases="WallaWalla"/>
      <Allow name="Wallowa" folder="Wallowa"/>
      <Allow name="Wenatchee" folder="Wenatchee"/>
      <Allow name="Willow" folder="Willow"/>
      <Allow name="Yankee Fork" folder="YankeeFork" aliases="YankeeFork"/>
    </Collection>
    <Collection id="COL_SITE" name="Site">
      <Allow pattern=".*"/>
    </Collection>
    <Collection id="COL_VISIT" name="Visit">
      <Allow pattern="[0-9]{4}"/>
    </Collection>
    <Collection id="COL_YEAR" name="Year">
      <Allow pattern="[0-9]{4}"/>
    </Collection>
    <Collection id="COL_FLOW" name="Flow">
      <Allow pattern=".*"/>
    </Collection>
  </Collections>
  
  <!--Groups are a lot simpler than collections. They can only be a single folder-->
  <Groups>
    <Group id="GRP_BASE" name="CHaMP" folder="CHaMP"/>
    <Group id="GRP_WATERSHED" name="Watershed" folder="Watershed"/>
    <Group id="GRP_NETWORK" name="Network" folder="Network"/>
    <Group id="GRP_SITE" name="Site" folder="Site"/>
    <Group id="GRP_YEAR" name="Year" folder="Year"/>
    <Group id="GRP_FLOW" name="Flow" folder="Flow"/>
    <Group id="GRP_TOPO" name="Topography" folder="Topography"/>
    <Group id="GRP_STREAMTEMP" name="Stream Temperature" folder="StreamTemp"/>
  </Groups>
  
  <!--Products for now just need ref, name and folder (url is optional and leads to a wiki)-->
  <Products>
    <Product id="QRF" name="QRF" folder="QRF" url=""/>
    
    <!--NETWORK level products-->
    <Product id="GRTS" name="GRTS" folder="GRTS" url=""/>
    <Product id="GAA" name="GAA" folder="GAA" url=""/>
    <Product id="CAD_Export" name="CAD Export" folder="CAD_Export" url=""/>
    <Product id="Substrate" name="Substrate" folder="Substrate" url=""/>
    <Product id="CONTEXT" name="Context Layers" folder="context_layers" url=""/>
    <Product id="VBET" name="VBET" folder="VBET" url=""/>
    <Product id="RVD" name="RVD" folder="RVD" url=""/>
    <Product id="RCA" name="RCA" folder="RCA" url=""/>
    <Product id="WRAT" name="WRAT" folder="WRAT" url=""/>
    <Product id="GPP" name="GPP" folder="GPP" url=""/>
    <Product id="CAPACITY" name="Capacity" folder="Capacity" url=""/>
    <Product id="CONFINEMENT" name="Confinement" folder="CONFINEMENT" url=""/>
    <Product id="EC" name="EC" folder="EC" url=""/>
    <Product id="Solar" name="Solar" folder="Solar" url=""/>
    <Product id="GNAT" name="GNAT" folder="GNAT" url=""/>
    <Product id="CHAMPMETRICS" name="CHaMP Metrics" folder="CHaMPMetrics" url=""/>
    
    <!--Streamtemp-->
    <Product id="STREAMTEMPMIN" name="STREAMTEMPMIN" folder="StreamTempMin" url=""/>
    <Product id="STREAMTEMPMAX" name="STREAMTEMPMAX" folder="StreamTempMax" url=""/>
    <Product id="STREAMTEMPMEAN" name="STREAMTEMPMEAN" folder="StreamTempMean" url=""/>
    <Product id="STREAMTEMPPOTMAX" name="STREAMTEMPPOTMAX" folder="StreamTempPotMax" url=""/>
    <Product id="STREAMTEMPPOTMEAN" name="STREAMTEMPPOTMEAN" folder="StreamTempPotMean" url=""/>
    <Product id="STREAMTEMPPOTMIN" name="STREAMTEMPPOTMIN" folder="StreamTempPotMin" url=""/>
    <!--Site-level products-->
    <Product id="SITE_HYDRO" name="Hydro" folder="Hydro" url=""/>
    <Product id="GCD" name="GCD" folder="GCD" url=""/>
    
    <!--Visit-level products-->
    <Product id="Topo" name="Topo" folder="Topo" url=""/>
    
    <!--Flow-level products-->
    <Product id="FHM" name="FHM" folder="FHM" url=""/>
    <Product id="GUT" name="GUT" folder="GUT" url=""/>
    <Product id="Hydro" name="Hydro" folder="Hydro" url=""/>
    <Product id="NREI" name="NREI" folder="NREI" url=""/>
    
    
  </Products>
</Definitions>

<!-- Here's where we specify the actual structure
  Reminder:
  - Collection: Repeating folders (e.g. Asotin, Lemhi
  - Group: Single folder with an explicit name (e.g. Topography)
  Rules:
  - Only one collection is allowed at any level
  - Collections cannot be mixed with groups or products
-->
<Hierarchy>
  <Group ref="GRP_BASE">
    <Product ref="QRF"/>
    <Product ref="CHAMPMETRICS" />
    <Product ref="GAA"/>
    <Product ref="CONTEXT"/>
    <Group ref="GRP_WATERSHED">
      <Collection ref="COL_WATERSHED">
        <Product ref="GRTS"/>
        <Group ref="GRP_NETWORK">
          <Product ref="VBET"/>
          <Product ref="RVD"/>
          <Product ref="RCA"/>
          <Product ref="WRAT"/>
          <Product ref="GPP"/>
          <Product ref="CAPACITY"/>
          <Product ref="CONFINEMENT"/>
          <Product ref="EC"/>
          <Product ref="Solar"/>
          <Product ref="GNAT"/>
          <Group ref="GRP_STREAMTEMP">
            <Collection ref="COL_YEAR">
              <Product ref="STREAMTEMPMIN"/>
              <Product ref="STREAMTEMPMAX"/>
              <Product ref="STREAMTEMPMEAN"/>              
              <Product ref="STREAMTEMPPOTMAX"/>
              <Product ref="STREAMTEMPPOTMIN"/>
              <Product ref="STREAMTEMPPOTMEAN"/>
            </Collection>
          </Group>
        </Group>
        <Group ref="GRP_SITE">
          <Collection ref="COL_SITE">
            <Product ref="GCD"/>
            <Product ref="FHM"/>
            <Product ref="SITE_HYDRO"/>
            <Product ref="NREI"/>
            <Group ref="GRP_YEAR">
              <Collection ref="COL_YEAR">
                <Collection ref="COL_VISIT">
                  <Group ref="GRP_FLOW">
                    <Collection ref="COL_FLOW">
                      <Product ref="Hydro"/>
                    </Collection>
                  </Group>
                  <Product ref="GUT"/>
                  <Product ref="Topo"/>
                  <Product ref="CAD_Export"/>
                  <Product ref="Substrate"/>
                </Collection>
              </Collection>
            </Group>
          </Collection>
        </Group>
      </Collection>
    </Group>
  </Group>
</Hierarchy>
</Program>

=== NorthArrowResearch/riverscapes-programs/BratOregon/program.xml
<?xml version="1.0" encoding="utf-8" ?>
<Program xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../XSD/V1/Program.xsd">

  <Name>Brat Oregon</Name>
  <MachineName>BRAT_OREGON</MachineName>
  
  <MetaData>
    <Meta name="projectfile">project.rs.xml</Meta>
    <Meta name="apiUrl">https://abgo77bhnc.execute-api.us-west-2.amazonaws.com/dev/api</Meta>
    <Meta name="projectXSD">https://raw.githubusercontent.com/NorthArrowResearch/riverscapes-programs/master/BratOregon/project/XSD/V1/Project.xsd</Meta>
  </MetaData>
  

  <Definitions>
    <!--Here's where we say what's allowed for each collection. Can be a list or a regex-->
    <Collections>
      <Collection id="COL_HUC8" name="HUC8">
          <Allow id="16040201" name="Upper Quinn" folder="16040201"/>
          <Allow id="16040205" name="Thousand-Virgin" folder="16040205"/>
          <Allow id="18010201" name="Williamson" folder="18010201"/>
          <Allow id="18010202" name="Sprague" folder="18010202"/>
          <Allow id="18010203" name="Upper Klamath Lake" folder="18010203"/>
          <Allow id="18010101" name="Smith" folder="18010101"/>
          <Allow id="18010205" name="Butte" folder="18010205"/>
          <Allow id="18010209" name="Lower Klamath" folder="18010209"/>
          <Allow id="17050117" name="Lower Malheur" folder="17050117"/>
          <Allow id="18010204" name="Lost" folder="18010204"/>
          <Allow id="18010206" name="Upper Klamath" folder="18010206"/>
          <Allow id="18020001" name="Goose Lake" folder="18020001"/>
          <Allow id="17100309" name="Applegate" folder="17100309"/>
          <Allow id="17100311" name="Illinois" folder="17100311"/>
          <Allow id="17100312" name="Chetco" folder="17100312"/>
          <Allow id="17120007" name="Warner Lakes" folder="17120007"/>
          <Allow id="17120008" name="Guano" folder="17120008"/>
          <Allow id="17100201" name="Necanicum" folder="17100201"/>
          <Allow id="17100202" name="Nehalem" folder="17100202"/>
          <Allow id="17100203" name="Wilson-Trusk-Nestuccu" folder="17100203"/>
          <Allow id="17100204" name="Siletz-Yaquina" folder="17100204"/>
          <Allow id="17100205" name="Alsea" folder="17100205"/>
          <Allow id="17100206" name="Siuslaw" folder="17100206"/>
          <Allow id="17100207" name="Siltcoos" folder="17100207"/>
          <Allow id="17100301" name="North Umpqua" folder="17100301"/>
          <Allow id="17100302" name="South Umpqua" folder="17100302"/>
          <Allow id="17100303" name="Umpqua" folder="17100303"/>
          <Allow id="17100304" name="Coos" folder="17100304"/>
          <Allow id="17100305" name="Coquille" folder="17100305"/>
          <Allow id="17100306" name="Sixes" folder="17100306"/>
          <Allow id="17100307" name="Upper Rogue" folder="17100307"/>
          <Allow id="17100308" name="Middle Rogue" folder="17100308"/>
          <Allow id="17100310" name="Lower Rogue" folder="17100310"/>
          <Allow id="17120001" name="Harney-Malheur Lakes" folder="17120001"/>
          <Allow id="17120002" name="Silvies" folder="17120002"/>
          <Allow id="17120003" name="Donner und Blitzen" folder="17120003"/>
          <Allow id="17120004" name="Silver" folder="17120004"/>
          <Allow id="17120005" name="Summer Lake" folder="17120005"/>
          <Allow id="17120006" name="Lake Abert" folder="17120006"/>
          <Allow id="17120009" name="Alvord Lake" folder="17120009"/>
          <Allow id="17100106" name="Willapa Bay" folder="17100106"/>
          <Allow id="17050103" name="Middle Snake-Succor" folder="17050103"/>
          <Allow id="17050107" name="Middle Owyhee" folder="17050107"/>
          <Allow id="17050108" name="Jordan" folder="17050108"/>
          <Allow id="17050115" name="Middle Snake-Payette" folder="17050115"/>
          <Allow id="17060101" name="Hells Canyon" folder="17060101"/>
          <Allow id="17050105" name="South Fork Owyhee" folder="17050105"/>
          <Allow id="17050106" name="East Little Owyhee" folder="17050106"/>
          <Allow id="17050109" name="Crooked-Rattlesnake" folder="17050109"/>
          <Allow id="17050110" name="Lower Owyhee" folder="17050110"/>
          <Allow id="17050116" name="Upper Malheur" folder="17050116"/>
          <Allow id="17050118" name="Bully" folder="17050118"/>
          <Allow id="17050119" name="Willow" folder="17050119"/>
          <Allow id="17050202" name="Burnt" folder="17050202"/>
          <Allow id="17050203" name="Powder" folder="17050203"/>
          <Allow id="17060102" name="Imnaha" folder="17060102"/>
          <Allow id="17060104" name="Upper Grande Ronde" folder="17060104"/>
          <Allow id="17060105" name="Wallowa" folder="17060105"/>
          <Allow id="17060106" name="Lower Grande Ronde" folder="17060106"/>
          <Allow id="17070103" name="Umatilla" folder="17070103"/>
          <Allow id="17070104" name="Willow" folder="17070104"/>
          <Allow id="17070201" name="Upper John Day" folder="17070201"/>
          <Allow id="17070202" name="North Fork John Day" folder="17070202"/>
          <Allow id="17070203" name="Middle Fork John Day" folder="17070203"/>
          <Allow id="17070204" name="Lower John Day" folder="17070204"/>
          <Allow id="17070301" name="Upper Deschutes" folder="17070301"/>
          <Allow id="17070302" name="Little Deschutes" folder="17070302"/>
          <Allow id="17070303" name="Beaver-South Fork" folder="17070303"/>
          <Allow id="17070304" name="Upper Crooked" folder="17070304"/>
          <Allow id="17070305" name="Lower Crooked" folder="17070305"/>
          <Allow id="17070306" name="Lower Deschutes" folder="17070306"/>
          <Allow id="17070307" name="Trout" folder="17070307"/>
          <Allow id="17090001" name="Middle Fork Willamette" folder="17090001"/>
          <Allow id="17090002" name="Coast Fork Willamette" folder="17090002"/>
          <Allow id="17090003" name="Upper Willamette" folder="17090003"/>
          <Allow id="17090004" name="Mckenzie" folder="17090004"/>
          <Allow id="17090005" name="North Santiam" folder="17090005"/>
          <Allow id="17090006" name="South Santiam" folder="17090006"/>
          <Allow id="17090007" name="Middle Willamette" folder="17090007"/>
          <Allow id="17090008" name="Yamhill" folder="17090008"/>
          <Allow id="17090009" name="Molalla-Pudding" folder="17090009"/>
          <Allow id="17090010" name="Tualatin" folder="17090010"/>
          <Allow id="17090011" name="Clackamas" folder="17090011"/>
          <Allow id="17050201" name="Brownlee Reservoir" folder="17050201"/>
          <Allow id="17060103" name="Lower Snake-Asotin" folder="17060103"/>
          <Allow id="17070101" name="Middle Columbia-Lake Wallula" folder="17070101"/>
          <Allow id="17070102" name="Walla Walla" folder="17070102"/>
          <Allow id="17070105" name="Middle Columbia-Hood" folder="17070105"/>
          <Allow id="17080001" name="Lower Columbia-Sandy" folder="17080001"/>
          <Allow id="17080003" name="Lower Columbia-Clatskanie" folder="17080003"/>
          <Allow id="17080006" name="Lower Columbia" folder="17080006"/>
          <Allow id="17090012" name="Lower Willamette" folder="17090012"/>
      </Collection>
      <Collection id="COL_HUC4" name="HUC4">
          <Allow id="1801" name="Klamath-Northern California Coastal" folder="1801"/>
          <Allow id="1802" name="Sacramento" folder="1802"/>
          <Allow id="1604" name="Black Rock Desert-Humboldt" folder="1604"/>
          <Allow id="1710" name="Oregon-Washington Coastal" folder="1710"/>
          <Allow id="1706" name="Lower Snake" folder="1706"/>
          <Allow id="1705" name="Middle Snake" folder="1705"/>
          <Allow id="1712" name="Oregon Closed Basins" folder="1712"/>
          <Allow id="1707" name="Middle Columbia" folder="1707"/>
          <Allow id="1708" name="Lower Columbia" folder="1708"/>
          <Allow id="1709" name="Willamette" folder="1709"/>
      </Collection>      
    </Collections>

    <!--Groups are a lot simpler than collections. They can only be a single folder-->
    <Groups>
      <Group id="GRP_NATIONAL" name="National" folder="National" />
      <Group id="GRP_HUC8" name="HUC8" folder="HUC8" />
      <Group id="GRP_HUC4" name="HUC4" folder="HUC4" />
    </Groups>

    <!--Products for now just need ref, name and folder (url is optional and leads to a wiki)-->
    <Products>
      <Product id="BRATModel4" name="BRAT Model (HUC4)" folder="BRAT" url="" />
      <Product id="BRATInputs4" name="BRAT Inputs (HUC4)" folder="BRATInputs" url="" />
      
      <Product id="BRATModel8" name="BRAT Models (HUC8)" folder="BRAT" url="" />
      <Product id="BRATInputs8" name="BRAT Inputs (HUC8)" folder="BRATInputs" url="" />

      <Product id="NationalDatasets" name="National Datasets" folder="nationaldatasets" url="" />

    </Products>
  </Definitions>

  <!-- Here's where we specify the actual structure
    Reminder:
      - Collection: Repeating folders (e.g. Asotin, Lemhi
      - Group: Single folder with an explicit name (e.g. Topography)
     Rules:
      - Only one collection is allowed at any level
      - Collections cannot be mixed with groups or products
  -->
  <Hierarchy>
    <Group ref="GRP_NATIONAL">
      <Product ref="NationalDatasets" />
    </Group>
    <Group ref="GRP_HUC4">
      <Collection ref="COL_HUC4">
        <Product ref="BRATModel4" />
        <Product ref="BRATInputs4" />
      </Collection>  
    </Group>
    <Group ref="GRP_HUC8">
      <Collection ref="COL_HUC8">
        <Product ref="BRATModel8" />
        <Product ref="BRATInputs8" />
      </Collection>  
    </Group>
  </Hierarchy>
</Program>
